import { FiCpu, FiInfo } from 'react-icons/fi';
import { buildInsights } from '../utils/insights';
import InsightIcon from '../components/dashboard/InsightIcon';
import useExpenseContext from '../context/ExpenseContext';
import EmptyState from '../components/common/EmptyState';

function AIInsights() {
  const { expenses, budget, settings } = useExpenseContext();
  const insights = buildInsights(expenses, budget, settings.currency, settings.income);

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">AI Insights</h1>
          <p className="page-subtitle">Smart analysis of your spending habits</p>
        </div>
      </div>

      <div className="card" style={{ marginBottom: 18 }}>
        <div className="card-header">
          <div className="card-title">
            <FiInfo /> How this works
          </div>
        </div>
        <p className="hint">
          Insights are generated by simple rules from your transaction history. A real AI model can
          be plugged in later to replace these mock insights.
        </p>
      </div>

      {insights.length === 0 ? (
        <div className="card">
          <EmptyState
            title="No insights yet"
            message="Add a few expenses so the app can learn your spending pattern."
          />
        </div>
      ) : (
        <div className="insights-grid">
          {insights.map((insight) => (
            <div className="insight-card" key={insight.id}>
              <div className={`insight-icon ${insight.type}`}>
                <InsightIcon icon={insight.icon} />
              </div>
              <div style={{ flex: 1 }}>
                <div className="insight-title">{insight.title}</div>
                <div className="insight-desc">{insight.description}</div>
                <div className="insight-tag">
                  <span className={`tag ${insight.type}`}>{insight.type}</span>
                </div>
                <span className="chip" style={{ marginLeft: 8 }}>
                  <FiCpu /> AI
                </span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default AIInsights;